In [6]:
import matplotlib.pyplot as plt
import base64
import httplib2
import os
from googleapiclient import discovery
from oauth2client.client import GoogleCredentials
import json
import pandas as pd

In [2]:
#請修改金鑰為自己的.json
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = '我是金鑰.json'
DISCOVERY_URL='https://{api}.googleapis.com/$discovery/rest?version={apiVersion}'
credentials = GoogleCredentials.get_application_default()
service = discovery.build('vision', 'v1', credentials=credentials,
                          discoveryServiceUrl=DISCOVERY_URL)

In [16]:
def get_labels(photo_file):
    with open(photo_file, 'rb') as image:
        image_content = base64.b64encode(image.read())
        service_request = service.images().annotate(body={
            'requests': [{
                'image': {
                    'content': image_content.decode('UTF-8')
                },
                'features': [{
                    'type': 'LABEL_DETECTION',
                    'maxResults': 20
                }]
            }]
        })
        response = service_request.execute()
        return response['responses'][0]['labelAnnotations']

In [ ]:
#網路上的範例，不需理會。https://github.com/enakai00/jupyter_gcp/blob/master/Vision%20API%20Quick%20Tour.ipynb
labels = get_labels('/Users/francislin/Desktop/Loan_FM/EDM_PHOTO/K01.jpg')
for label in labels:
    print ('%s : %2d%%' % (label['description'], label['score']*100))

In [17]:
#一個圖組有多張照片，透過for loop將全部的資訊辨識一遍
append_df = pd.DataFrame(columns=['description', 'score'])
for i in range(1,7):
    pre_label=get_labels("/Users/francislin/Desktop/Loan_FM/EDM_PHOTO/K0%i.jpg"%(i))
    aa= json.dumps(pre_label)
    df= pd.read_json(aa)
    pre_trans = (df.drop(['mid','topicality'], axis=1))
    append_df = append_df.append(pre_trans, ignore_index=True)

In [18]:
#接續合併結果，將相同的label annotation取平均
label= (append_df.groupby(by='description', as_index=True).agg({'score': pd.Series.mean})).sort_values(by='score',ascending=False)
Set_K= label.transpose()
Set_K['Photo_key']='K'
Set_K.columns = Set_K.columns.str.replace(' ','_')
Set_K

description,text,feature_phone,mobile_phone,product,shoulder,gadget,smartphone,communication_device,font,communication,...,online_advertising,media,graphic_design,logo,neck,table,telephone,presentation,computer_wallpaper,Photo_key
score,0.89352,0.866861,0.821791,0.803396,0.796073,0.728786,0.667423,0.658675,0.655326,0.624101,...,0.561368,0.543246,0.532048,0.524469,0.523782,0.521808,0.517601,0.50834,0.501227,K

In [19]:
append_df = pd.DataFrame(columns=['description', 'score'])
for i in range(1,8):
    pre_label=get_labels("/Users/francislin/Desktop/Loan_FM/EDM_PHOTO/L0%i.jpg"%(i))#Should change Set
    aa= json.dumps(pre_label)
    df= pd.read_json(aa)
    pre_trans = (df.drop(['mid','topicality'], axis=1))
    append_df = append_df.append(pre_trans, ignore_index=True)
label= (append_df.groupby(by='description', as_index=True).agg({'score': pd.Series.mean})).sort_values(by='score',ascending=False)
Set_L= label.transpose()#Should change Set
Set_L['Photo_key']='L'#Should change Set
Set_L.columns = Set_L.columns.str.replace(' ','_')#Should change Set
Set_L#Should change Set

description,cartoon,text,yellow,art,orange,font,product,graphic_design,line,organism,...,graphics,brand,number,logo,organization,computer_wallpaper,angle,online_advertising,pattern,Photo_key
score,0.960169,0.945756,0.943615,0.828348,0.802713,0.797409,0.745578,0.740704,0.734417,0.696448,...,0.573827,0.569728,0.569158,0.56854,0.563242,0.56304,0.553909,0.525483,0.50967,L

In [20]:
append_df = pd.DataFrame(columns=['description', 'score'])
for i in range(1,10):
    pre_label=get_labels("/Users/francislin/Desktop/Loan_FM/EDM_PHOTO/M0%i.jpg"%(i))#Should change Set
    aa= json.dumps(pre_label)
    df= pd.read_json(aa)
    pre_trans = (df.drop(['mid','topicality'], axis=1))
    append_df = append_df.append(pre_trans, ignore_index=True)
label= (append_df.groupby(by='description', as_index=True).agg({'score': pd.Series.mean})).sort_values(by='score',ascending=False)
Set_M= label.transpose()#Should change Set
Set_M['Photo_key']='M'#Should change Set
Set_M.columns = Set_M.columns.str.replace(' ','_')#Should change Set
Set_M#Should change Set

description,text,yellow,product,font,technology,software,line,area,design,document,...,number,graphics,organization,angle,multimedia,computer_icon,media,website,rectangle,Photo_key
score,0.933457,0.905115,0.79816,0.774513,0.759963,0.726552,0.713491,0.67201,0.671311,0.662108,...,0.575291,0.570179,0.557215,0.550872,0.547243,0.533813,0.532897,0.527907,0.522978,M

In [21]:
append_df = pd.DataFrame(columns=['description', 'score'])
for i in range(1,10):
    pre_label=get_labels("/Users/francislin/Desktop/Loan_FM/EDM_PHOTO/N0%i.jpg"%(i))#Should change Set
    aa= json.dumps(pre_label)
    df= pd.read_json(aa)
    pre_trans = (df.drop(['mid','topicality'], axis=1))
    append_df = append_df.append(pre_trans, ignore_index=True)
label= (append_df.groupby(by='description', as_index=True).agg({'score': pd.Series.mean})).sort_values(by='score',ascending=False)
Set_N= label.transpose()#Should change Set
Set_N['Photo_key']='N'#Should change Set
Set_N.columns = Set_N.columns.str.replace(' ','_')#Should change Set
Set_N#Should change Set

description,text,yellow,product,font,technology,line,software,advertising,document,arm,...,number,organization,graphics,angle,website,multimedia,media,computer_icon,rectangle,Photo_key
score,0.925907,0.905115,0.789758,0.771266,0.748849,0.718728,0.700507,0.687293,0.686384,0.676481,...,0.572674,0.562123,0.558758,0.550557,0.547355,0.547243,0.540075,0.533813,0.522978,N

In [22]:
append_df = pd.DataFrame(columns=['description', 'score'])
for i in range(1,2):
    pre_label=get_labels("/Users/francislin/Desktop/Loan_FM/EDM_PHOTO/O0%i.jpg"%(i))#Should change Set
    aa= json.dumps(pre_label)
    df= pd.read_json(aa)
    pre_trans = (df.drop(['mid','topicality'], axis=1))
    append_df = append_df.append(pre_trans, ignore_index=True)
label= (append_df.groupby(by='description', as_index=True).agg({'score': pd.Series.mean})).sort_values(by='score',ascending=False)
Set_O= label.transpose()#Should change Set
Set_O['Photo_key']='O'#Should change Set
Set_O.columns = Set_O.columns.str.replace(' ','_')#Should change Set
Set_O#Should change Set

description,text,yellow,web_page,font,line,product,online_advertising,area,website,logo,brand,graphics,screenshot,paper,diagram,document,Photo_key
score,0.964241,0.954383,0.924547,0.864879,0.766555,0.735602,0.72867,0.67201,0.651031,0.643499,0.578677,0.53125,0.523322,0.518648,0.517928,0.504658,O

In [23]:
append_df = pd.DataFrame(columns=['description', 'score'])
for i in range(1,10):
    pre_label=get_labels("/Users/francislin/Desktop/Loan_FM/EDM_PHOTO/P0%i.jpg"%(i))#Should change Set
    aa= json.dumps(pre_label)
    df= pd.read_json(aa)
    pre_trans = (df.drop(['mid','topicality'], axis=1))
    append_df = append_df.append(pre_trans, ignore_index=True)
label= (append_df.groupby(by='description', as_index=True).agg({'score': pd.Series.mean})).sort_values(by='score',ascending=False)
Set_P= label.transpose()#Should change Set
Set_P['Photo_key']='P'#Should change Set
Set_P.columns = Set_P.columns.str.replace(' ','_')#Should change Set
Set_P#Should change Set

description,text,yellow,product,font,technology,software,line,area,screenshot,logo,...,advertising,angle,graphics,joint,website,computer_icon,media,rectangle,illustration,Photo_key
score,0.916426,0.905115,0.795324,0.759152,0.739722,0.733837,0.711391,0.67201,0.66612,0.665446,...,0.55558,0.554161,0.551745,0.537128,0.536879,0.533813,0.526463,0.522979,0.516503,P

In [24]:
VisionAPI_result_AJ = pd.read_csv("過去做A到J圖組的結果.csv", encoding='BIG5')

In [27]:
VisionAPI_result = VisionAPI_result_AJ.append([Set_K,Set_L,Set_M,Set_N,Set_O,Set_P], ignore_index=True)
VisionAPI_result = VisionAPI_result.fillna(0)
VisionAPI_result

/usr/local/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,Photo_key,abdomen,advertising,angle,aqua,area,arm,art,balloon,banner,...,telephone,text,tree,vehicle,water,web_page,website,window,wood,yellow
0,A,0.000000,0.000000,0.556662,0.000000,0.67201,0.000000,0.501495,0.000000,0.000000,...,0.000000,0.931069,0.000000,0.000000,0.000000,0.567786,0.000000,0.000000,0.000000,0.915875
1,B,0.000000,0.599300,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.886970,0.000000,0.000000,0.000000,0.000000,0.729745,0.000000,0.000000,0.000000
2,C,0.000000,0.677787,0.550082,0.000000,0.67201,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.920666,0.000000,0.000000,0.730932,0.514882,0.681263,0.000000,0.000000,0.930897
3,D,0.000000,0.000000,0.556662,0.000000,0.67201,0.000000,0.501495,0.000000,0.000000,...,0.000000,0.931069,0.000000,0.000000,0.000000,0.567786,0.000000,0.000000,0.000000,0.915875
4,E,0.000000,0.635014,0.547988,0.880111,0.67201,0.681158,0.000000,0.000000,0.000000,...,0.000000,0.898479,0.000000,0.000000,0.000000,0.000000,0.623590,0.671078,0.000000,0.000000
5,F,0.553239,0.541439,0.559333,0.000000,0.67201,0.678238,0.000000,0.000000,0.000000,...,0.000000,0.910855,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,G,0.000000,0.000000,0.571757,0.000000,0.67201,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.914867,0.000000,0.000000,0.000000,0.000000,0.553448,0.000000,0.622648,0.000000
7,H,0.000000,0.000000,0.550313,0.000000,0.67201,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.965785,0.792416,0.550452,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,I,0.000000,0.000000,0.574753,0.000000,0.67201,0.000000,0.000000,0.915130,0.000000,...,0.000000,0.965308,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,J,0.000000,0.606056,0.572825,0.000000,0.67201,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.935335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,K,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.517601,0.893520,0.000000,0.000000,0.000000,0.000000,0.614480,0.000000,0.000000,0.000000
11,L,0.000000,0.689069,0.553909,0.000000,0.67201,0.000000,0.828348,0.573958,0.589044,...,0.000000,0.945756,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.943615
12,M,0.000000,0.635073,0.550872,0.000000,0.67201,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.933457,0.000000,0.000000,0.000000,0.602410,0.527907,0.000000,0.000000,0.905115
13,N,0.000000,0.687293,0.550557,0.000000,0.67201,0.676481,0.000000,0.000000,0.000000,...,0.000000,0.925907,0.000000,0.000000,0.000000,0.596573,0.547355,0.000000,0.000000,0.905115
14,O,0.000000,0.000000,0.000000,0.000000,0.67201,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.964241,0.000000,0.000000,0.000000,0.924547,0.651031,0.000000,0.000000,0.954383
15,P,0.000000,0.555580,0.554161,0.000000,0.67201,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.916426,0.000000,0.000000,0.000000,0.617481,0.536879,0.000000,0.000000,0.905115