In [1]:
# load package
import numpy as np
import pandas as pd
import pickle

# set path
import os
default_path = "/Users/francislin/temp/"
os.chdir(default_path)

# skip interaction warning
import warnings; 
warnings.filterwarnings('ignore')
#你可以选择修改 ast_note_iteractively kernel 选项来使得 Jupyter 为每一行的变量或语句执行这个操作，以便你可以立即看到多条语句一起输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
with open('all_data.pickle','rb') as f:
    df= pickle.load(f)

In [3]:
df.head()

,cuisine,id,used_pepper,used_salt,used_oil,used_garlic,used_ground,used_fresh,used_sauce,used_sugar,...,used_hock,used_rose,used_ciabatta,used_ready,used_regular,used_glass,used_safflower,used_jeera,used_Oil,used_oven
0,greek,10259,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,southern_us,25693,1,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,filipino,20130,1,1,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,indian,22213,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,indian,13162,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
data_key=df[['id','cuisine']]
data = df.drop(['id','cuisine'],axis=1)

In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.5, svd_solver='full')
pca_data=pca.fit(data)

In [9]:
print(pca.n_components_)

33

In [10]:
principalComponents = pca.fit_transform(data)
principalDf = pd.DataFrame(data = principalComponents, columns = ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33'])

In [11]:
principalDf.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V24,V25,V26,V27,V28,V29,V30,V31,V32,V33
0,0.410868,1.511810,-1.369136,0.115075,-0.188099,-0.200973,-1.101218,-0.015127,-0.308410,-0.153127,...,0.395455,0.347953,0.249483,-0.114691,0.695470,1.015662,0.236217,-1.110846,-0.402731,-0.441971
1,0.034862,0.394947,0.930672,-0.360164,-0.105215,-1.337149,-0.073493,0.389514,-0.206608,0.806345,...,0.179808,-0.731184,0.104983,0.185974,-0.216569,0.600367,-0.734708,0.045187,-0.424181,0.204273
2,0.332297,-0.650574,0.725765,1.004397,0.015120,-0.228537,-1.393389,-0.231589,0.290304,-0.210332,...,0.028039,0.261609,0.266571,0.562182,-0.414371,0.195020,-0.608727,0.155030,0.142926,-0.164911
3,-1.303200,-0.633279,-0.821922,-0.810094,-0.343640,-0.631985,-0.309213,0.482228,0.143415,0.786575,...,-0.422225,0.246944,-0.448853,-0.382434,-0.228812,-0.139839,-0.033913,0.084564,0.043698,0.393276
4,0.996157,0.313401,2.253926,0.395730,-0.994413,0.220015,-0.237783,-0.917451,1.639429,-0.105104,...,-0.010676,0.792023,-0.505657,-0.253466,0.179617,-0.548353,-0.032707,-0.459137,0.213715,-0.192434

In [12]:
ALL = pd.concat([data_key, principalDf], axis=1)

In [14]:
ALL.head()

,id,cuisine,V1,V2,V3,V4,V5,V6,V7,V8,...,V24,V25,V26,V27,V28,V29,V30,V31,V32,V33
0,10259,greek,0.410868,1.511810,-1.369136,0.115075,-0.188099,-0.200973,-1.101218,-0.015127,...,0.395455,0.347953,0.249483,-0.114691,0.695470,1.015662,0.236217,-1.110846,-0.402731,-0.441971
1,25693,southern_us,0.034862,0.394947,0.930672,-0.360164,-0.105215,-1.337149,-0.073493,0.389514,...,0.179808,-0.731184,0.104983,0.185974,-0.216569,0.600367,-0.734708,0.045187,-0.424181,0.204273
2,20130,filipino,0.332297,-0.650574,0.725765,1.004397,0.015120,-0.228537,-1.393389,-0.231589,...,0.028039,0.261609,0.266571,0.562182,-0.414371,0.195020,-0.608727,0.155030,0.142926,-0.164911
3,22213,indian,-1.303200,-0.633279,-0.821922,-0.810094,-0.343640,-0.631985,-0.309213,0.482228,...,-0.422225,0.246944,-0.448853,-0.382434,-0.228812,-0.139839,-0.033913,0.084564,0.043698,0.393276
4,13162,indian,0.996157,0.313401,2.253926,0.395730,-0.994413,0.220015,-0.237783,-0.917451,...,-0.010676,0.792023,-0.505657,-0.253466,0.179617,-0.548353,-0.032707,-0.459137,0.213715,-0.192434

In [15]:
os.chdir('/Users/francislin/temp/')
import pickle
with open('all_data_pca33.pickle','wb') as f:
    pickle.dump(ALL,f)